export const assets=[
    {
        status:'success',
        assetId:1,
        assetName:"asset1",
        channelId:2,
        sectionId:123,
        subSectionId:123,
        Categoryid:1,
        subcategoryid:25,
        Tags:"exclusive",
        Partner:'pitsop',
        Assettype:8,
        fileName1:'file 2',
        fileName2:"file 2",
        startDate: new Date(),
        endDate: new Date(),
        vehicleType:2,
    },
    {
        status:'success',
        assetId:2,
        assetName:"asset2",
        channelId:2,
        sectionId:123,
        subSectionId:123,
        Categoryid:2,
        subcategoryid:25,
        Tags:"amazing",
        Partner:'ceat',
        Assettype:8,
        fileName1:'file 2',
        fileName2:"file 2",
        startDate: new Date(),
        endDate: new Date(),
        vehicleType:2,
    },
    {
        status:'success',
        assetId:3,
        assetName:"asset3",
        channelId:2,
        sectionId:123,
        subSectionId:123,
        Categoryid:3,
        subcategoryid:25,
        Tags:"amazing",
        Partner:'scad',
        Assettype:8,
        fileName1:'file 2',
        fileName2:"file 2",
        startDate: new Date(),
        endDate: new Date(),
        vehicleType:4,
    },
    {
        status:'success',
        assetId:4,
        assetName:"asset4",
        channelId:2,
        sectionId:123,
        subSectionId:123,
        Categoryid:3,
        subcategoryid:25,
        Tags:"amazing",
        Partner:'batterywale',
        Assettype:8,
        fileName1:'file 2',
        fileName2:"file 2",
        startDate: new Date(),
        endDate: new Date(),
        vehicleType:4,
    },
    {
        status:'success',
        assetId:5,
        assetName:"asset5",
        channelId:2,
        sectionId:123,
        subSectionId:123,
        Categoryid:3,
        subcategoryid:25,
        Tags:"amazing",
        Partner:'batterywale',
        Assettype:8,
        fileName1:'file 2',
        fileName2:"file 2",
        startDate: new Date(),
        endDate: new Date(),
        vehicleType:4,
    },
]

export const assets2=[
    {
        vehicle:2,
        category:1,
        brand:1,
    },
    {
        vehicle:2,
        category:2,
        brand:1
    },
    {
        vehicle:2,
        category:2,
        brand:2
    },
    {
        vehicle:2,
        category:1,
        brand:2
    },
    {
        vehicle:4,
        category:1,
        brand:1
    },
    {
        vehicle:4,
        category:2,
        brand:1
    },
    {
        vehicle:4,
        category:2,
        brand:2
    },
    {
        vehicle:4,
        category:1,
        brand:2
    },
]